version: '3.1'

networks:
  n11bootcamp:

services:
  # DB and Queue -----------------------
  cassandra:
    image: postgres
    container_name: n11-pg-server
    hostname: n11-pg-server
    networks:
      - n11bootcamp
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: N11_FINALPROJECT

  backend:
    image: n11-backend
    container_name: n11-backend-server
    hostname: n11-backend-server
    restart: always
    networks:
      - n11bootcamp
    ports:
      - '8082:8082'

  frontend:
    image: n11-frontend
    container_name: n11-frontend-server
    hostname: n11-frontend-server
    restart: always
    networks:
      - n11bootcamp
    ports:
      - '9092:80'